### ISSUE TITLE
Gif Generator

### ISSUE THREAD

**Issue by LiamMyles** [LiamMyles/playing-with-polygons#40]
Would be great to have a way to generate a gif of the screen, and then allow the user to post that to twitter or save it.

**TODO List**
- [x] Pull two modal components in app into their own components
- [x] Move Gif class construction from draw to modal component
- [x] Gif Component to handle start/abort/finished/porgress events
- [x] Gif component should have a slider to how long the gif should be
- [x] Update draw functions to reuse more code across them. So less places need to change to keep it consistent.
- [x] Refactor component draw to use 30 fps and adujst randomize default speeds
- [x] Try to come up with better typing for the GIF

**Comment by LiamMyles** [comment]
Looking into this, it looks like my best option is going to be to use Gif.js - https://github.com/jnordberg/gif.js

What I'm thinking of doing is render a new canvas offscreen whos sole reason to exist to to render gifs. That way it doesn't cause any problems with the other canvas.

Some things to note about Gif.js
- Keep the delay at 20 (https://github.com/jnordberg/gif.js/issues/116)
- there is an on "finished" as well as a on "progress" which is useful for a loading bar.
- The size of the image seems to have the largest impact on render time
